name: Build && Deploy Spring Boot Greeting
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
      - name: Build app using maven
        run: "mvn -DskipTest=true -Pnative clean package"
      - name: Done!
        run: echo !Done